# Generated by Django 6.0.7 on 2026-08-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['comment', 'created_at'], name='comments_at_comment_5dbad7_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(models.OrderBy(models.F('created_at'), descending=True), name='cmt_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(models.F('reply_to'), models.OrderBy(models.F('created_at'), descending=True), name='cmt_reply_created_idx'),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['comment', 'reaction'], name='comments_re_comment_bc1852_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='comments_us_usernam_055f58_idx'),
        ),
    ]
